modLoader = "javafml"
loaderVersion = "[36,)"
license = "MIT"
[[mods]]
modId = "theothershoretravel"
version = "${file.jarVersion}"
displayName = "TheOtherShore Travel"
logoFile="logo.png"
authors = "游京秋惜"
description = "想要留住雪花。但在手心里，它只会融化的更快"